# Generated by Django 3.0 on 2019-12-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('total_score', models.IntegerField()),
            ],
            options={
                'db_table': 'event_table',
                'managed': False,
            },
        ),
    ]
